version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: logwatcher-mysql
    environment:
      MYSQL_ROOT_PASSWORD: logwatcher123
      MYSQL_DATABASE: logwatcher
      MYSQL_USER: logwatcher
      MYSQL_PASSWORD: logwatcher123
    ports:
      - "23307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: logwatcher-redis
    ports:
      - "26379:6379"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: logwatcher-backend
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_URL=mysql+pymysql://logwatcher:logwatcher123@mysql:3306/logwatcher
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "28000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: logwatcher-frontend
    depends_on:
      - backend
    ports:
      - "23000:3000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped

volumes:
  mysql_data: 